before_script:
  # install ssh-agent
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
  # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  cache:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - vuepress build blog
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - mv dist /var/static_blog
