language: node_js
node_js: stable
install:
- npm install
cache:
  npm: true
  directories:
  - node_modules
script:
- vuepress build blog
dd:
- openssl aes-256-cbc -K $encrypted_65e0afb8e021_key -iv $encrypted_65e0afb8e021_iv
  -in travis.enc -out travis -d
